#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPPartInfo.h"


@protocol ASPPage
@end

@interface ASPPage : ASPObject


@property(nonatomic) NSString* pageText;

@property(nonatomic) NSArray<ASPPartInfo>* parts;

@end
