#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPPage.h"


@protocol ASPPagesInfo
@end

@interface ASPPagesInfo : ASPObject


@property(nonatomic) NSArray<ASPPage>* pages;

@end
