#import <Foundation/Foundation.h>
#import "ASPOCRResponse.h"
#import "ASPObject.h"
#import "ASPApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface ASPOcrApi: NSObject

@property(nonatomic, assign)ASPApiClient *apiClient;

-(instancetype) initWithApiClient:(ASPApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(ASPOcrApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
///
///
/// Recognize image text from some url if provided or from the request body content, language can be selected, default dictionaries can be used for correction.
/// 
///
/// @param url The image file url.
/// @param language Language of the document.
/// @param useDefaultDictionaries Use default dictionaries for result correction.
/// @param file 
/// 
///
/// @return ASPOCRResponse*
-(NSNumber*) postOcrFromUrlOrContentWithCompletionBlock :(NSString*) url 
     language:(NSString*) language 
     useDefaultDictionaries:(NSNumber*) useDefaultDictionaries 
     file:(NSURL*) file 
    
    completionHandler: (void (^)(ASPOCRResponse* output, NSError* error))completionBlock;
    


///
///
/// Recognize image text, language and text region can be selected, default dictionaries can be used for correction.
/// 
///
/// @param name Name of the file to recognize.
/// @param language Language of the document.
/// @param rectX Top left point X coordinate of Rectangle to recognize text inside.
/// @param rectY Top left point Y coordinate of Rectangle to recognize text inside.
/// @param rectWidth Width of Rectangle to recognize text inside.
/// @param rectHeight Height of Rectangle to recognize text inside.
/// @param useDefaultDictionaries Use default dictionaries for result correction.
/// @param storage Image&#39;s storage.
/// @param folder Image&#39;s folder.
/// 
///
/// @return ASPOCRResponse*
-(NSNumber*) getRecognizeDocumentWithCompletionBlock :(NSString*) name 
     language:(NSString*) language 
     rectX:(NSNumber*) rectX 
     rectY:(NSNumber*) rectY 
     rectWidth:(NSNumber*) rectWidth 
     rectHeight:(NSNumber*) rectHeight 
     useDefaultDictionaries:(NSNumber*) useDefaultDictionaries 
     storage:(NSString*) storage 
     folder:(NSString*) folder 
    
    completionHandler: (void (^)(ASPOCRResponse* output, NSError* error))completionBlock;
    



@end
